namespace: default
release_version: 0.1.0

replicaCount: 1

image:
  tag: 548
  repository: mmcacr1.azurecr.io/boardgame
  pullPolicy: IfNotPresent
service:
  port: 8080

appName: boardgame
versionLabel: stable

selectorRole: stable

stablecanary:
    stable:
      tag: "23"
      replicaCount: 2
      weight: 100
    canary:
      tag: "23"
      replicaCount: 2
      weight: 0

gateway:
  enabled: false
virtualService:
  enabled: false
destinationRule:
  enabled: false
svc:
  enabled: false
