trigger:
  none

pool:
  name: Avivapool

parameters:
  - name: environment
    displayName: Environment Name
    type: string
    default: dev
    values:
      - dev
      - uat
      - perf
      - prod

variables:
  - template: envfiles/${{ parameters.environment }}.yaml

stages:
- stage: Build_Stage
  displayName: Build Stage
  jobs:
  - job: Build_Job
    displayName: Build Job
    steps:
    - script: |
        set -e

        echo "Loading config for environment: ${{ parameters.environment }}"

        command -v jq >/dev/null || { echo "jq is required but not installed"; exit 1; }

        JSON_PATH="$(Build.SourcesDirectory)/envfiles/envconfig.json"
        ENV=$(echo "${{ parameters.environment }}" | tr '[:upper:]' '[:lower:]')

        RESOURCE_GROUP=$(jq -r ".\"$ENV\".RG_name" "$JSON_PATH")
        NAMESPACE=$(jq -r ".\"$ENV\".namespace" "$JSON_PATH")
        CLUSTERNAME=$(jq -r ".\"$ENV\".clustername" "$JSON_PATH")
        TAG=$(jq -r ".\"$ENV\".tag" "$JSON_PATH")
        DEPLOYMENT_NAME=$(jq -r ".\"$ENV\".deploymentname" "$JSON_PATH")

        for var in RESOURCE_GROUP NAMESPACE CLUSTERNAME TAG DEPLOYMENT_NAME; do
          if [ -z "${!var}" ] || [ "${!var}" = "null" ]; then
            echo "Missing value for $var in envconfig.json"
            exit 1
          fi
        done

        echo "##vso[task.setvariable variable=resourceGroup;isOutput=true]$RESOURCE_GROUP"
        echo "##vso[task.setvariable variable=namespace;isOutput=true]$NAMESPACE"
        echo "##vso[task.setvariable variable=clustername;isOutput=true]$CLUSTERNAME"
        echo "##vso[task.setvariable variable=deploymentname;isOutput=true]$DEPLOYMENT_NAME"
        echo "##vso[task.setvariable variable=tag;isOutput=true]$TAG"
      name: SetEnvVars
      displayName: Load environment variables

    - task: Maven@4
      displayName: Maven Build
      inputs:
        mavenPomFile: pom.xml
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: JDKVersion
        mavenVersionOption: Default
        sonarQubeRunAnalysis: false

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        command: buildAndPush
        Dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
          
- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build_Stage
  variables:
    resourceGroup: $[ dependencies.Build_Stage.outputs['Build_Job.SetEnvVars.resourceGroup'] ]
    namespace: $[ dependencies.Build_Stage.outputs['Build_Job.SetEnvVars.namespace'] ]
    clustername: $[ dependencies.Build_Stage.outputs['Build_Job.SetEnvVars.clustername'] ]
    deploymentname: $[ dependencies.Build_Stage.outputs['Build_Job.SetEnvVars.deploymentname'] ]
    tag: $[ dependencies.Build_Stage.outputs['Build_Job.SetEnvVars.tag'] ]
    environment: ${{ parameters.environment }}

  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: ${{ parameters.environment }}_Approve
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: Login & Get AKS Credentials
            inputs:
              azureSubscription: fd-Service-Connection
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az aks get-credentials \
                  --name $(clustername) \
                  --resource-group $(resourceGroup) \
                  --overwrite-existing

                kubectl get nodes

          - script: |
              if ! command -v helm >/dev/null; then
                curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
              fi

              helm plugin install https://github.com/databus23/helm-diff || true
            displayName: Install Helm & Helm Diff

          - script: |
              HELMFILE_VERSION=v1.1.4
              curl -LO https://github.com/helmfile/helmfile/releases/download/${HELMFILE_VERSION}/helmfile_1.1.4_linux_amd64.tar.gz
              tar -xzf helmfile_1.1.4_linux_amd64.tar.gz
              chmod +x helmfile
              sudo mv helmfile /usr/local/bin/helmfile
              helmfile --version
            displayName: Install Helmfile

          - script: |
              git config --global url."https://$(HELMREPO)@github.com/".insteadOf "https://github.com/"
              git clone https://github.com/rajalearn90/HelmfileRepo.git
            displayName: Clone Helmfile Repo

          - script: |
              set -e
              cd HelmfileRepo

              echo "Running Helmfile DIFF..."
              helmfile -e $(environment) diff \
                --context 3

            displayName: Helmfile Diff (Pre-Deploy Gate)

          - script: |
              set -e
              cd HelmfileRepo

              echo "Running Helmfile Dry Run..."
              helmfile -e $(environment) apply \
                --dry-run

            displayName: Helmfile Dry Run

          - script: |
              set -e
              cd HelmfileRepo

              echo "Deploying to $(environment)..."
              helmfile -e $(environment) apply \
                --atomic \
                --timeout 10m

            displayName: Helmfile Apply (Atomic Deploy)
